project:
  type: default

format:
  revealjs:
    embed-resources: true
    theme: default
    logo: ../assets/fus-logo.png
    css: ../assets/custom.scss
    slideNumber: true
    incremental: true
    transition: fade

execute:
  echo: true
  warning: false



